# Generated by Django 4.1.5 on 2023-01-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phonenumber',
            field=models.IntegerField(default=9999999999),
            preserve_default=False,
        ),
    ]
