# Generated by Django 4.2.9 on 2024-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
